try:

except Exception as e:
    print(e)